# Generated by Django 2.2.12 on 2020-10-21 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MidPointObjectType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=50)),
                ('rest_name', models.CharField(max_length=50)),
                ('common_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('oid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('version', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('objectType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RBACRisk.MidPointObjectType')),
            ],
        ),
    ]
