# Generated by Django 2.2.12 on 2021-02-07 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RBACRisk', '0003_auto_20210109_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='midPoint',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='objectType',
        ),
        migrations.DeleteModel(
            name='MidPointObjectType',
        ),
        migrations.DeleteModel(
            name='Resource',
        ),
    ]
