# Generated by Django 2.2.12 on 2021-02-08 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RBACRisk', '0005_midpoint_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='RBACModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('midPointId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RBACRisk.MidPoint')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
