# Generated by Django 2.2.12 on 2021-02-13 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RBACRisk', '0006_rbacmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='RBACUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rbacModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RBACRisk.RBACModel')),
            ],
        ),
    ]
