# Generated by Django 2.2.12 on 2021-02-15 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RBACRisk', '0007_rbacuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='RBACRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rbacModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RBACRisk.RBACModel')),
                ('rbacUser', models.ManyToManyField(to='RBACRisk.RBACUser')),
            ],
        ),
        migrations.CreateModel(
            name='RBACPerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rbacModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RBACRisk.RBACModel')),
                ('rbacRole', models.ManyToManyField(to='RBACRisk.RBACRole')),
            ],
        ),
    ]
