# Generated by Django 2.2.12 on 2021-02-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RBACRisk', '0009_auto_20210215_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='rbacrole',
            name='oid',
            field=models.UUIDField(default=0),
        ),
        migrations.AddField(
            model_name='rbacuser',
            name='oid',
            field=models.UUIDField(default=0),
        ),
    ]
