# Generated by Django 2.2.12 on 2021-02-15 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RBACRisk', '0010_auto_20210215_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='rbacperm',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
