# Generated by Django 2.2.12 on 2021-02-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RBACRisk', '0011_rbacperm_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rbacperm',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
    ]
