# Generated by Django 2.2.12 on 2021-02-15 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RBACRisk', '0012_auto_20210215_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rbacperm',
            name='description',
            field=models.CharField(default='', max_length=500, null=True),
        ),
    ]
