# Generated by Django 2.2.12 on 2021-02-15 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RBACRisk', '0013_auto_20210215_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rbacmodel',
            name='midPointId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RBACRisk.MidPoint'),
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rbacModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RBACRisk.RBACModel')),
            ],
        ),
    ]
