# Generated by Django 2.2.12 on 2021-02-15 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RBACRisk', '0014_auto_20210215_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rbacuser',
            name='rbacRoles',
            field=models.ManyToManyField(related_name='rbacUsers', to='RBACRisk.RBACRole'),
        ),
    ]
