# Generated by Django 2.2.12 on 2021-02-15 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RBACRisk', '0015_auto_20210215_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rbacrole',
            name='rbacPerms',
            field=models.ManyToManyField(related_name='rbacRoles', to='RBACRisk.RBACPerm'),
        ),
    ]
