# Generated by Django 2.2.12 on 2021-02-16 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RBACRisk', '0016_auto_20210215_2328'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisPerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(default='', max_length=500, null=True)),
                ('riskProbability', models.FloatField()),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RBACRisk.Analysis')),
                ('rbacPerm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RBACRisk.RBACPerm')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('oid', models.UUIDField(default=0)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RBACRisk.Analysis')),
                ('analysisPerms', models.ManyToManyField(related_name='analysisRoles', to='RBACRisk.AnalysisPerm')),
                ('rbacRole', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RBACRisk.RBACRole')),
            ],
        ),
    ]
