# Generated by Django 2.2.12 on 2021-02-16 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RBACRisk', '0017_analysisperm_analysisrole'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('oid', models.UUIDField(default=0)),
                ('riskProbability', models.FloatField()),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RBACRisk.Analysis')),
                ('analysisRoles', models.ManyToManyField(related_name='analysisUsers', to='RBACRisk.AnalysisRole')),
                ('rbacUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RBACRisk.RBACUser')),
            ],
        ),
    ]
