# Generated by Django 2.2.12 on 2021-02-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RBACRisk', '0019_auto_20210216_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rbacperm',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
