# Generated by Django 2.2.12 on 2021-02-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RBACRisk', '0020_auto_20210216_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='rbacperm',
            name='oid',
            field=models.UUIDField(default=0),
        ),
    ]
