# Generated by Django 3.1.6 on 2021-02-18 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RBACRisk', '0022_rbacperm_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='rbacrole',
            name='rbacRole',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RBACRisk.rbacrole'),
        ),
    ]
