# Generated by Django 3.1.6 on 2021-02-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RBACRisk', '0023_rbacrole_rbacrole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rbacrole',
            name='rbacRole',
        ),
        migrations.AddField(
            model_name='rbacrole',
            name='subRoles',
            field=models.ManyToManyField(null=True, related_name='_rbacrole_subRoles_+', to='RBACRisk.RBACRole'),
        ),
    ]
