# Generated by Django 3.1.6 on 2021-02-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RBACRisk', '0024_auto_20210218_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rbacrole',
            name='subRoles',
            field=models.ManyToManyField(related_name='_rbacrole_subRoles_+', to='RBACRisk.RBACRole'),
        ),
    ]
