# Generated by Django 3.1.6 on 2021-02-18 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RBACRisk', '0025_auto_20210218_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rbacrole',
            name='subRoles',
        ),
    ]
