# Generated by Django 3.1.6 on 2021-02-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RBACRisk', '0026_remove_rbacrole_subroles'),
    ]

    operations = [
        migrations.AddField(
            model_name='rbacrole',
            name='subRoles',
            field=models.ManyToManyField(to='RBACRisk.RBACRole'),
        ),
    ]
